DROP DATABASE IF EXISTS employee_db;

CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department (

  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL

);

CREATE TABLE role (

  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(7,2) NOT NULL,
  departmentId INT,
  FOREIGN KEY (department_id) REFERENCES department (id)
  
);

CREATE TABLE employee (

  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(30) NOT NULL,
  lastName VARCHAR(30) NOT NULL,
  roleId INT NOT NULL,
  FOREIGN KEY (roleId) REFERENCES role (id),
);